#!/usr/bin/env bash
genesis="$(cd "$(dirname "$0")/.." && pwd -P)"
source "$genesis/modules/common"

title "Homebrew"

if test ! "$(command -v brew)"
then
  info "Install Homebrew"
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
  info "Update Homebrew"
  brew update
fi

info "Install Homebrew formulas"
brew tap "homebrew/bundle" 2> /dev/null
brew tap "homebrew/cask-versions" 2> /dev/null
brew bundle --file="$genesis/assets/Brewfile"

info "Cleanup Homebrew"
brew cleanup
