#!/usr/bin/env bash
genesis="$(cd "$(dirname "$0")/.." && pwd -P)"
source "$genesis/modules/common"

# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'

###############################################################################
title "Trackpad, Mouse, Keyboard, Bluetooth"
###############################################################################

info "Accelerate cursor"
defaults write NSGlobalDomain KeyRepeat -int 2

info "Enable full keyboard access for all controls"
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

###############################################################################
title "Finder"
###############################################################################

info "Expose hidden files and Library folder in Finder"
defaults write com.apple.finder AppleShowAllFiles -bool true
chflags nohidden ~/Library

info "Empty Trash securely by default"
defaults write com.apple.finder EmptyTrashSecurely -bool true

info "Show all filename extensions"
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

info "Disable window animations and Get Info animations"
defaults write com.apple.finder DisableAllAnimations -bool true

info "Show status bar"
defaults write com.apple.finder ShowStatusBar -bool true

info "Keep folders on top when sorting by name"
defaults write com.apple.finder _FXSortFoldersFirst -bool true

info "Disable the warning when changing a file extension"
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

info "Avoid creating .DS_Store files on network or USB volumes"
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

info "Use list view in all Finder windows by default"
# Four-letter codes for the other view modes: `icnv`, `clmv`, `Flwv`
defaults write com.apple.finder FXPreferredViewStyle Nlsv

info "Disable the warning before emptying the Trash"
defaults write com.apple.finder WarnOnEmptyTrash -bool false

###############################################################################
title "Dock, Dashboard, and Hot Corners"
###############################################################################

info "Wipe all (default) app icons from the Dock"
defaults write com.apple.dock persistent-apps -array

info "Add standard applications to Dock"
for app in \
  Mail \
  Firefox
do
  defaults write com.apple.dock "persistent-apps" -array-add "<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/$app.app/</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>"
done

info "Minimize windows into their application’s icon"
defaults write com.apple.dock minimize-to-application -bool true

info "Show only open applications in the Dock"
defaults write com.apple.dock static-only -bool true

info "Don’t animate opening applications from the Dock"
defaults write com.apple.dock launchanim -bool false

info "Change minimize/maximize window effect"
defaults write com.apple.dock mineffect -string "scale"

# Hot corners - Possible values:
#  0: no-op
#  2: Mission Control
#  3: Show application windows
#  4: Desktop
#  5: Start screen saver
#  6: Disable screen saver
#  7: Dashboard
# 10: Put display to sleep
# 11: Launchpad
# 12: Notification Center
info "Top left screen corner → Mission Control"
defaults write com.apple.dock wvous-tl-corner -int 2
defaults write com.apple.dock wvous-tl-modifier -int 0
info "Top right screen corner → Notification Center"
defaults write com.apple.dock wvous-tr-corner -int 12
defaults write com.apple.dock wvous-tr-modifier -int 0
info "Bottom left screen corner → Launchpad"
defaults write com.apple.dock wvous-bl-corner -int 11
defaults write com.apple.dock wvous-bl-modifier -int 0
info "Bottom left screen corner → Desktop"
defaults write com.apple.dock wvous-br-corner -int 4
defaults write com.apple.dock wvous-br-modifier -int 0

###############################################################################
title "UI / UX"
###############################################################################

info "Set menubar to dark mode"
osascript -e 'tell application "System Events" to tell appearance preferences to set dark mode to true'

info "Set sidebar icon size to medium"
defaults write NSGlobalDomain NSTableViewDefaultSizeMode -int 1

info "Automatically quit printer app once the print jobs complete"
defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

info "Remove duplicates in the 'Open With' menu"
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user

#info "Restart automatically if the computer freezes"
#sudo systemsetup -setrestartfreeze on

info "Use scroll gesture with the control (^) modifier key to zoom"
defaults write com.apple.universalaccess closeViewScrollWheelToggle -bool true

info "Increase keyboard repeat rate"
defaults write NSGlobalDomain KeyRepeat -int 2
defaults write NSGlobalDomain InitialKeyRepeat -int 15

###############################################################################
title "Activity Monitor"
###############################################################################

info "Show all processes in Activity Monitor"
defaults write com.apple.ActivityMonitor ShowCategory -int 100

###############################################################################
title "Mac App Store"
###############################################################################

info "Turn on app auto-update"
defaults write com.apple.commerce AutoUpdate -bool true

###############################################################################
title "FileVault"
###############################################################################

info "Enable FileVault"
if [[ $(sudo fdesetup isactive) = false ]]
then
    echo ''
    read -p "##### Do you want to enable Disk Encryption? [y/n]" -n 1 -r
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo ''
        sudo fdesetup enable
    else
        echo ''
    fi
fi
