#!/usr/bin/env bash
genesis="$(cd "$(dirname "$0")/.." && pwd -P)"
source "$genesis/modules/common"

title "Setup Fish Shell"
chsh -s /usr/bin/fish
fish

info "Install fisher package manager"
curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs https://git.io/fisher

fisher add fzf 
fisher add fzy 
fisher add z 
fisher add edc/bass
fisher add decors/fish-colored-man
fisher add decors/fish-colors
