#!/usr/bin/env bash
genesis="$(cd "$(dirname "$0")/.." && pwd -P)"
source "$genesis/modules/common"

title "Python Packages"

info "Installing pip2 packages"
sudo pip2 install -r "$genesis/assets/packages.pip2"

info "Installing pip3 packages"
sudo pip3 install -r "$genesis/assets/packages.pip3"
